In [2]:
import pandas as pd

In [3]:
def change_age(age_column_value):
    """
    Receives an age value with the format years-days
    :param age_column_value
    :return: The age in years only
    """

    # Split the string by '-' and take the first part
    age = age_column_value.split('-')[0]
    # Convert to int
    return int(age)


def country_to_continent(country_name):
    """
    Receives country name and converts it to continent name where it belongs to
    :param country_name
    :return: continent name
    """

    country_continent_mapping = {
        'Argentina': 'South America',
        'Australia': 'Oceania',
        'Belgium': 'Europe',
        'Brazil': 'South America',
        'Cameroon': 'Africa',
        'Canada': 'North America',
        'Costa Rica': 'North America',
        'Croatia': 'Europe',
        'Denmark': 'Europe',
        'Ecuador': 'South America',
        'England': 'Europe',
        'France': 'Europe',
        'Germany': 'Europe',
        'Ghana': 'Africa',
        'Iran': 'Asia',
        'IR Iran': 'Asia',
        'Japan': 'Asia',
        'Korea Republic': 'Asia',
        'Mexico': 'North America',
        'Morocco': 'Africa',
        'Netherlands': 'Europe',
        'Poland': 'Europe',
        'Portugal': 'Europe',
        'Qatar': 'Asia',
        'Saudi Arabia': 'Asia',
        'Senegal': 'Africa',
        'Serbia': 'Europe',
        'Spain': 'Europe',
        'Switzerland': 'Europe',
        'Tunisia': 'Africa',
        'United States': 'North America',
        'Uruguay': 'South America',
        'Wales': 'Europe'
    }

    country_continent_name = country_continent_mapping.get(country_name, 'Unknown')

    return country_continent_name

In [4]:
player_keepers = pd.read_csv("Data/FIFA World Cup 2022 Player Data/player_keepers.csv")
player_keepersadv = pd.read_csv("Data/FIFA World Cup 2022 Player Data/player_keepersadv.csv")
player_defense = pd.read_csv("Data/FIFA World Cup 2022 Player Data/player_defense.csv")
player_stats = pd.read_csv("Data/FIFA World Cup 2022 Player Data/player_stats.csv")
player_misc = pd.read_csv("Data/FIFA World Cup 2022 Player Data/player_misc.csv")
player_gca = pd.read_csv("Data/FIFA World Cup 2022 Player Data/player_gca.csv")
player_passing = pd.read_csv("Data/FIFA World Cup 2022 Player Data/player_passing.csv")
player_shooting = pd.read_csv("Data/FIFA World Cup 2022 Player Data/player_shooting.csv")
player_possession = pd.read_csv("Data/FIFA World Cup 2022 Player Data/player_possession.csv")
player_defense.head()

,player,position,team,age,birth_year,minutes_90s,tackles,tackles_won,tackles_def_3rd,tackles_mid_3rd,...,dribbles_vs,dribble_tackles_pct,dribbled_past,blocks,blocked_shots,blocked_passes,interceptions,tackles_interceptions,clearances,errors
0,Aaron Mooy,MF,Australia,32-094,1990,4.0,9.0,6,4.0,4.0,...,8.0,75.0,2.0,6.0,4.0,2.0,3,12.0,9.0,0.0
1,Aaron Ramsey,MF,Wales,31-357,1990,3.0,2.0,0,0.0,2.0,...,2.0,0.0,2.0,4.0,1.0,3.0,0,2.0,2.0,1.0
2,Abdelhamid Sabiri,MF,Morocco,26-020,1996,2.0,3.0,1,1.0,2.0,...,6.0,33.3,4.0,3.0,1.0,2.0,5,8.0,3.0,0.0
3,Abdelkarim Hassan,DF,Qatar,29-112,1993,3.0,7.0,3,5.0,2.0,...,4.0,75.0,1.0,3.0,1.0,2.0,1,8.0,5.0,0.0
4,Abderrazak Hamdallah,FW,Morocco,32-001,1990,0.8,0.0,0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0,0.0,2.0,0.0

In [5]:
deleted_players = ['Ismail Mohamad','Kevin RodrÃ­guez','Yahya Jabrane']

In [6]:
defenders_data = player_defense[player_defense['position'] == 'DF'][player_defense['minutes_90s'] > (15/90)][['player', 'age', 'minutes_90s',
                            'team', 'position', 'tackles','tackles_won', 'dribble_tackles_pct', 'blocked_passes', 'blocked_shots']]
defenders_data = defenders_data[~defenders_data['player'].isin(deleted_players)]
defenders_data = pd.merge(defenders_data, player_stats[['player', 'club']], on='player', how='left')
defenders_data = pd.merge(defenders_data, player_misc[['player', 'aerials_won_pct']], on='player', how='left')
defenders_data = pd.merge(defenders_data, player_passing[['player', 'passes_pct']], on='player', how='left')
defenders_data['tackles'] = defenders_data['tackles_won'] / defenders_data['tackles'].replace(0, 1)
defenders_data['blocked_passes'] = defenders_data['blocked_passes'] / defenders_data['minutes_90s'].replace(0, 1)
defenders_data['blocked_shots'] = defenders_data['blocked_shots'] / defenders_data['minutes_90s'].replace(0, 1)
defenders_data = defenders_data.drop(columns=['tackles', 'tackles_won'])    
defenders_data["age"] = defenders_data["age"].apply(change_age)
defenders_data["team_cont"] = defenders_data["team"].apply(country_to_continent)
defenders_data.to_csv('defenders_data.csv', index=False)

C:\Users\ariam\AppData\Local\Temp\ipykernel_4212\2957324821.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  defenders_data = player_defense[player_defense['position'] == 'DF'][player_defense['minutes_90s'] > (15/90)][['player', 'age', 'minutes_90s',

In [7]:
defenders_data.head()

,player,age,minutes_90s,team,position,dribble_tackles_pct,blocked_passes,blocked_shots,club,aerials_won_pct,passes_pct,team_cont
0,Abdelkarim Hassan,29,3.0,Qatar,DF,75.0,0.666667,0.333333,Al Sadd SC,75.0,75.8,Asia
1,Abdou Diallo,26,3.7,Senegal,DF,100.0,0.000000,0.270270,RB Leipzig,53.8,74.7,Africa
2,Abdulelah Al-Amri,25,2.0,Saudi Arabia,DF,0.0,0.500000,0.500000,Al-Nassr,71.4,71.2,Asia
3,Abdullah Madu,29,0.5,Saudi Arabia,DF,NaN,2.000000,4.000000,Al-Nassr,50.0,38.5,Asia
4,Abolfazl Jalali,24,0.2,IR Iran,DF,NaN,0.000000,0.000000,Esteghlal,NaN,69.0,Asia

In [8]:
midfielders_data = player_defense[player_defense['position'] == 'FW'][player_defense['minutes_90s'] > (15/90)][['player', 'age',
                                                         'minutes_90s', 'team', 'position', 'tackles', 'tackles_won', 'interceptions']]
midfielders_data = midfielders_data[~midfielders_data['player'].isin(deleted_players)]
midfielders_data = pd.merge(midfielders_data, player_stats[['player', 'club', 'goals_assists_per90']], on='player', how='left')
midfielders_data = pd.merge(midfielders_data, player_passing[['player', 'passes_pct']], on='player', how='left')
midfielders_data = pd.merge(midfielders_data, player_possession[['player', 'dribbles_completed_pct']], on='player', how='left')
midfielders_data = pd.merge(midfielders_data, player_gca[['player', 'sca_per90']], on='player', how='left')
midfielders_data['tackles'] = midfielders_data['tackles_won'] / midfielders_data['tackles'].replace(0, 1)
midfielders_data['interceptions'] = midfielders_data['interceptions'] / midfielders_data['minutes_90s'].replace(0, 1)
midfielders_data = midfielders_data.drop(columns=['tackles_won'])    
midfielders_data["age"] = midfielders_data["age"].apply(change_age)
midfielders_data["team_cont"] = midfielders_data["team"].apply(country_to_continent)
midfielders_data.to_csv('midfielders_data.csv', index=False)

C:\Users\ariam\AppData\Local\Temp\ipykernel_4212\2024695984.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  midfielders_data = player_defense[player_defense['position'] == 'FW'][player_defense['minutes_90s'] > (15/90)][['player', 'age',

In [9]:
midfielders_data.head()

,player,age,minutes_90s,team,position,tackles,interceptions,club,goals_assists_per90,passes_pct,dribbles_completed_pct,sca_per90,team_cont
0,Abderrazak Hamdallah,32,0.8,Morocco,FW,0.000000,0.00000,Al-Ittihad,0.00,53.3,66.7,0.00,Africa
1,Abdessamad Ezzalzouli,21,1.0,Morocco,FW,0.666667,0.00000,Osasuna,0.00,76.9,50.0,5.63,Africa
2,Akram Afif,26,3.0,Qatar,FW,0.000000,0.00000,Al Sadd SC,0.00,84.2,42.9,2.33,Asia
3,Aleksandar MitroviÄ‡,28,2.9,Serbia,FW,0.000000,0.00000,Fulham,0.69,78.3,100.0,1.03,Europe
4,Alexis Vega,25,2.1,Mexico,FW,0.000000,0.47619,Guadalajara,0.00,71.4,25.0,1.87,North America

In [10]:
attackers_data = player_defense[player_defense['position'] == 'MF'][player_defense['minutes_90s'] > (15/90)][['player', 'age',
                                                                         'minutes_90s', 'team', 'position', 'tackles_interceptions']]
attackers_data = attackers_data[~attackers_data['player'].isin(deleted_players)]
attackers_data = pd.merge(attackers_data, player_stats[['player', 'club', 'goals_assists_per90']], on='player', how='left')
attackers_data = pd.merge(attackers_data, player_passing[['player', 'passes_pct']], on='player', how='left')
attackers_data = pd.merge(attackers_data, player_gca[['player', 'sca_per90']], on='player', how='left')
attackers_data = pd.merge(attackers_data, player_possession[['player', 'dribbles_completed_pct']], on='player', how='left')
attackers_data = pd.merge(attackers_data, player_shooting[['player', 'shots_on_target_pct']], on='player', how='left')
attackers_data['tackles_interceptions'] = attackers_data['tackles_interceptions'] / attackers_data['minutes_90s'].replace(0, 1)
attackers_data["age"] = attackers_data["age"].apply(change_age)
attackers_data["team_cont"] = attackers_data["team"].apply(country_to_continent)
attackers_data.to_csv('attackers_data.csv', index=False)

C:\Users\ariam\AppData\Local\Temp\ipykernel_4212\443346096.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  attackers_data = player_defense[player_defense['position'] == 'MF'][player_defense['minutes_90s'] > (15/90)][['player', 'age',

In [11]:
attackers_data.head()

,player,age,minutes_90s,team,position,tackles_interceptions,club,goals_assists_per90,passes_pct,sca_per90,dribbles_completed_pct,shots_on_target_pct,team_cont
0,Aaron Mooy,32,4.0,Australia,MF,3.000000,Celtic,0.0,78.3,1.25,66.7,0.0,Oceania
1,Aaron Ramsey,31,3.0,Wales,MF,0.666667,Nice,0.0,78.6,1.02,25.0,0.0,Europe
2,Abdelhamid Sabiri,26,2.0,Morocco,MF,4.000000,Sampdoria,0.5,77.6,2.40,0.0,0.0,Africa
3,Abdulaziz Hatem,32,2.2,Qatar,MF,0.909091,Al Rayyan SC,0.0,79.1,0.92,100.0,100.0,Asia
4,Abdulellah Al-Malki,28,1.9,Saudi Arabia,MF,2.631579,Al-Hilal,0.0,78.6,1.03,NaN,0.0,Asia

In [12]:
keepers_data = player_keepers[player_keepers['minutes_90s'] > (15/90)][['player', 'team', 'age', 'club', 'position',
                                                                         'minutes_90s', 'gk_clean_sheets_pct','gk_save_pct', 'gk_pens_save_pct']]
keepers_data = keepers_data[~keepers_data['player'].isin(deleted_players)]
keepers_data = pd.merge(keepers_data, player_keepersadv[['player', 'gk_passes_pct_launched', 'gk_crosses_stopped_pct']], on='player', how='left')
keepers_data = pd.merge(keepers_data, player_passing[['player', 'passes_pct']], on='player', how='left')
keepers_data["age"] = keepers_data["age"].apply(change_age)
keepers_data["team_cont"] = keepers_data["team"].apply(country_to_continent)
keepers_data.to_csv('keepers_data.csv', index=False)

In [13]:
keepers_data.head()

,player,team,age,club,position,minutes_90s,gk_clean_sheets_pct,gk_save_pct,gk_pens_save_pct,gk_passes_pct_launched,gk_crosses_stopped_pct,passes_pct,team_cont
0,Aimen Dahmen,Tunisia,25,CS Sfaxien,GK,3.0,66.7,90.0,NaN,36.6,0.0,62.3,Africa
1,Alireza Beiranvand,IR Iran,30,Persepolis,GK,1.2,0.0,80.0,NaN,31.3,0.0,64.5,Asia
2,Alisson,Brazil,30,Liverpool,GK,4.2,50.0,71.4,NaN,35.7,0.0,86.0,South America
3,Andries Noppert,Netherlands,28,Heerenveen,GK,5.3,40.0,86.4,0.0,40.0,9.5,81.8,Europe
4,AndrÃ© Onana,Cameroon,26,Inter,GK,0.9,0.0,66.7,NaN,30.0,0.0,76.3,Africa